#simple
echo "AAAAAA" | ./A2P1.out 
#length tests
echo "AA" | ./A2P1.out 
echo "TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" | ./A2P1.out
#filter test 
echo "TTT%%%%%GGGGGaaaaaaaCCCCC^^^^^AAAAAA" | ./A2P1.out 
#limit test
echo "TAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT" | ./A2P1.out 
